### ISSUE TITLE
Manually change application description

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/city_of_sydney#5]
https://www.planningalerts.org.au/admin/applications/528363 has an inaccurate description, caused by council entering the wrong data when the DA was created. Council's site has been updated and the owner has requested we also correct the inaccurate data the Council provided.

Please also document how this manual edit can be done in the rails console so this can be a standard task in future :)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nhid)

**Comment by mlandauer** [comment]
This is an issue on the application not a scraper issue so I've opened a new ticket. So, closing this one.
